# Generated by Django 5.0.2 on 2024-03-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TastyCakes', '0006_black_cur_cake_blue_cake_chocolate_cake_pine_cake_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=50)),
                ('Contact_no', models.IntegerField(verbose_name=12)),
                ('Password', models.TextField()),
            ],
        ),
    ]
