# Generated by Django 5.0.2 on 2024-03-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TastyCakes', '0007_account_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_name', models.CharField(max_length=255)),
                ('cake_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('name', models.CharField(max_length=255)),
                ('Contact_no', models.IntegerField(verbose_name=12)),
                ('address', models.TextField(max_length=255)),
            ],
        ),
    ]
