# Generated by Django 5.0.2 on 2024-03-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TastyCakes', '0009_alter_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Contact_no',
            new_name='Contact',
        ),
    ]
